#!/bin/sh

DIR=$1
APP_JAR="vhosts.jar"
APP_NAME="vhosts"
JAVA_HOME="/Users/orion/Library/Java/JavaVirtualMachines/openjdk-14.0.2/Contents/Home"
ICNS=$1/../Resources/application.icns

cd "$DIR" || exit
$JAVA_HOME/bin/java --module-path /Library/Java/javafx-sdk-14.0.2.1/lib/ --add-modules javafx.controls,javafx.fxml -Xdock:name="$APP_NAME" -Xdock:icon="$ICNS" -cp "$DIR;.;" -jar "$DIR/$APP_JAR"
# /Users/orion/Library/Java/JavaVirtualMachines/openjdk-14.0.2/Contents/Home